[package]
name = "PostForMe"
version = "0.1.0"

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework", rev = "61d920a2bccb431c89588e2db69991a3819eed3a" }
# You don't need to specify standard library
# MoveStdlib = { git = "https://github.com/MystenLabs/sui.git", subdir="crates/sui-framework/deps/move-stdlib", rev = "61d920a2bccb431c89588e2db69991a3819eed3a" }

[addresses]
sui = "0x2"
openrails = "0x0"