[package]
name = "TxAuthority"
version = "0.1.0"

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework", rev = "devnet" }
SuiUtils = { git = "https://github.com/0xnoots/sui-utils.git", subdir = "package", rev = "master" }

[addresses]
sui_playground = "0x0"